# Generated by Django 2.2.12 on 2021-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('reporter', models.CharField(max_length=40)),
                ('news_header', models.CharField(max_length=200)),
                ('news', models.TextField()),
            ],
        ),
    ]
